title: "HS GitHub Documentation"
description: "A website using Just the Docs theme"
url: "https://haricharan12.github.io"
baseurl: "/hs-github.io"  # Matches the repository name
theme: "just-the-docs"