title: "HS GitHub Documentation"
description: "A website using Just the Docs theme"
url: "https://haricharan12-github.io"
baseurl: ""  # Leave this empty for user/organization pages
theme: "just-the-docs"